version: "3.7"
services:
  database:
    container_name: stone_db
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  db_migrations:
    image: migrate/migrate
    container_name: db_migrations
    volumes:
      - ./migrations:/migrations
    depends_on:
      - database
    command: -source=file://migrations -database postgres://postgres:banana@database:5432/stone_db?sslmode=disable up
  server:
    container_name: stone_server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: